service: golf-pool-api

frameworkVersion: '2 || 3'

provider:
  name: aws
  region: ${opt:region, 'invalid'}
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiKeys:
    - ${self:service}-key
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: ${ssm:/jimstick-golf-pool/players-table/arn}
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Scan'
        - Effect: 'Allow'
          Resource: ${ssm:/jimstick-golf-pool/gents-table/arn}
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Scan'

functions:
  fetchLeaderboard:
    handler: fetchLeaderboard.handler
    environment:
      PLAYERS_TABLE: ${ssm:/jimstick-golf-pool/players-table/name}
      GENTS_TABLE: ${ssm:/jimstick-golf-pool/gents-table/name}
    events:
      - http:
          method: GET
          path: /leaderboard
          private: true
  # placePicks:
  #   handler: placePicks.handler
  #   environment:
  #     GENTS_TABLE: ${ssm:/jimstick-golf-pool/gents-table/name}
  #   events:
  #     - httpApi:
  #         method: PUT
  #         path: /picks
  # pollScores:
  #   handler: pollScores.handler
  #   environment:
  #     PLAYERS_TABLE: ${ssm:/jimstick-golf-pool/players-table/name}
  #   events:
  #     - schedule:
  #         rate: rate(5 minutes)
  #         enabled: true
