service: golf-pool-api

frameworkVersion: '2 || 3'

provider:
  name: aws
  region: ${opt:region, 'invalid'}
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: ${ssm:/jimstick-golf-pool/leaderboard-table/arn}
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Scan'
        - Effect: 'Allow'
          Resource: ${ssm:/jimstick-golf-pooll/picks-table/arn}
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Scan'

functions:
  fetchLeaderboard:
    handler: fetchLeaderboard.handler
    environment:
      LEADERBOARD_TABLE: ${ssm:/jimstick-golf-pool/leaderboard-table/name}
      PICKS_TABLE: ${ssm:/jimstick-golf-pool/picks-table/name}
    events:
      - httpApi:
          method: GET
          path: /leaderboard
  placePicks:
    handler: placePicks.handler
    environment:
      PICKS_TABLE: ${ssm:/jimstick-golf-pool/picks-table/name}
    events:
      - httpApi:
          method: PUT
          path: /picks
  pollScores:
    handler: pollScores.handler
    environment:
      LEADERBOARD_TABLE: ${ssm:/jimstick-golf-pool/leaderboard-table/name}
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
