service: golf-pool-api

frameworkVersion: '2 || 3'

provider:
  name: aws
  region: ${opt:region, 'invalid'}
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  apiGateway:
    apiKeys:
      - ${self:service}-key
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: ${ssm:/jimstick-golf-pool/players-bucket/arn}
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
        - Effect: 'Allow'
          Resource: ${ssm:/jimstick-golf-pool/gents-table/arn}
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Scan'

functions:
  fetchLeaderboard:
    handler: fetchLeaderboard.handler
    environment:
      GENTS_TABLE: ${ssm:/jimstick-golf-pool/gents-table/name}
      PLAYERS_BUCKET: ${ssm:/jimstick-golf-pool/players-bucket/name}
    events:
      - http:
          method: GET
          path: /leaderboard
          private: true
  # placePicks:
  #   handler: placePicks.handler
  #   environment:
  #     GENTS_TABLE: ${ssm:/jimstick-golf-pool/gents-table/name}
  #   events:
  #     - httpApi:
  #         method: PUT
  #         path: /picks
  pollScores:
    handler: pollScores.handler
    environment:
      PLAYERS_BUCKET: ${ssm:/jimstick-golf-pool/players-bucket/name}
    # events:
    #   - schedule:
    #       rate: rate(5 minutes)
    #       enabled: true
